#Config file for the Dialer App

#Settings for the Originate command to the Manager API
channel: IAX2/teliax/
context: nightbell_playback
extension: 1000
priority: 0
callerid: NightBell
timeout: 43200000
actionid: nightbell
async: TRUE 
relaunch_timeout: 20 #In seconds, so set to 9 minutes now

